distribution      = "rockylinux"
arch              = "amd64"
os_version        = "8"
image_version     = "1.0.2"
app_version       = "1.16.0"
image_directory   = "/tmp/images/"
dns_search_domain = "search example.com"
dns_1             = "192.168.0.1"
dns_2             = "192.168.1.1"
application       = "LLama2"

################### VERSIONS ####################
consul_version = "1.15.3"
nomad_version = "1.6.1"
vault_version = "1.8.2"
waypoint_version = "0.11.4"
boundary_version = "0.13.1"